baseURL = "https://WoShiQingqing.github.io/myblog/"   # 先随便写，之后换成 GitHub Pages 地址
canonifyURLs = true
relativeURLs = true

languageCode = "en-us"
title = "清的博客"
theme = "PaperMod"

[pagination]
  pageSize = 5

[params]
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto" # 自动切换亮/暗色
